Source/AutoGene/Presentation/Host/Controllers/Ecommerce/EcommerceController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Business.Contracts.Services.GeneEditor;
using Business.Contracts.ViewModels.GeneEditor;
using Presentation.Common.Controllers;
using Presentation.Common.Security;

namespace AutoGene.Presentation.Host.Controllers.CycleEditor
{
    //[AuthorizeUser(UserRoles = "Guest,Admin")]
    public class EcommerceController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source/AutoGene/Presentation/Host/Controllers/Ecommerce/GeneOrderController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Business.Contracts.Services.GeneEditor;
using Business.Contracts.ViewModels.GeneEditor;
using Presentation.Common.Controllers;

namespace AutoGene.Presentation.Host.Controllers.Ecommerce
{
    //[AuthorizeUser(UserRoles = "Guest,Admin")]
    public class GeneOrderController : BaseController
    {
        private readonly IGeneEditorService geneEditorService;

        public GeneOrderController(IGeneEditorService geneEditorService)
        {
            this.geneEditorService = geneEditorService;
        }

        [HttpPost]
        public async Task<ActionResult> Index(string genesProjectName)
        {
            GeneEditorViewModel geneEditorViewModel = await geneEditorService.GetGeneEditorViewModel();

            return View(geneEditorViewModel);
        }

        [HttpPost]
        public async Task<JsonResult> OptimizeGene(GeneEditorViewModel geneEditorViewModel)
        {
            //            if (string.IsNullOrWhiteSpace(geneEditorViewModel.ProteinInitialSequence) &&
            //                (string.IsNullOrWhiteSpace(geneEditorViewModel.DNAInitialSequence) || geneEditorViewModel.DNAInitialSequence.Length % 3 != 0))
            //            {
            //                ModelState.AddModelError(string.Empty, "Wrong sequence");
            //                return View(geneEditorViewModel);
            //            }

            //            ModelState.Clear();
            try
            {
                geneEditorViewModel = await geneEditorService.OptimizeDNASequence(geneEditorViewModel);
                return Json(geneEditorViewModel);
            }
            catch (Exception ex)
            {
                return JsonError();
            }
        }

        [HttpPost]
        public async Task<JsonResult> UpdateGeneFragments(GeneEditorViewModel geneEditorViewModel)
        {
            await geneEditorService.UpdateGeneFragments(
                geneEditorViewModel.GeneId, geneEditorViewModel.OptimizedDNASequence,
                geneEditorViewModel.GeneFragmentLength, geneEditorViewModel.GeneFragmentOverlappingLength,
                geneEditorViewModel.KPlusConcentration, geneEditorViewModel.DMSO);

            return JsonSuccess(geneEditorViewModel.GeneId);
        }

        [HttpGet]
        public JsonResult GetGeneEditorViewModel(string geneId)
        {
            GeneEditorViewModel geneEditorViewModel = geneEditorService.GetGeneEditorViewModel(geneId);
            return Json(geneEditorViewModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> DeleteGene(string geneId)
        {
            await geneEditorService.DeleteGene(geneId);

            return JsonSuccess(geneId);
        }
    }
}

Source/AutoGene/Presentation/Host/Controllers/Ecommerce/OrderGenesController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Business.Contracts.Services.GeneEditor;
using Business.Contracts.ViewModels.GeneEditor;
using Presentation.Common.Controllers;

namespace AutoGene.Presentation.Host.Controllers.Ecommerce
{
    //[AuthorizeUser(UserRoles = "Guest,Admin")]
    public class OrderGenesController : BaseController
    {
        private readonly IGeneEditorService geneEditorService;

        public OrderGenesController(IGeneEditorService geneEditorService)
        {
            this.geneEditorService = geneEditorService;
        }

        [HttpPost]
        public async Task<ActionResult> Index(string genesProjectName)
        {
            GeneEditorViewModel geneEditorViewModel = await geneEditorService.GetGeneEditorViewModel();

            return View(geneEditorViewModel);
        }

        [HttpPost]
        public async Task<JsonResult> OptimizeGene(GeneEditorViewModel geneEditorViewModel)
        {
            //            if (string.IsNullOrWhiteSpace(geneEditorViewModel.ProteinInitialSequence) &&
            //                (string.IsNullOrWhiteSpace(geneEditorViewModel.DNAInitialSequence) || geneEditorViewModel.DNAInitialSequence.Length % 3 != 0))
            //            {
            //                ModelState.AddModelError(string.Empty, "Wrong sequence");
            //                return View(geneEditorViewModel);
            //            }

            //            ModelState.Clear();
            try
            {
                geneEditorViewModel = await geneEditorService.OptimizeDNASequence(geneEditorViewModel);
                return Json(geneEditorViewModel);
            }
            catch (Exception ex)
            {
                return JsonError();
            }
        }

        [HttpPost]
        public async Task<JsonResult> UpdateGeneFragments(GeneEditorViewModel geneEditorViewModel)
        {
            await geneEditorService.UpdateGeneFragments(
                geneEditorViewModel.GeneId, geneEditorViewModel.OptimizedDNASequence,
                geneEditorViewModel.GeneFragmentLength, geneEditorViewModel.GeneFragmentOverlappingLength,
                geneEditorViewModel.KPlusConcentration, geneEditorViewModel.DMSO);

            return JsonSuccess(geneEditorViewModel.GeneId);
        }

        [HttpGet]
        public JsonResult GetGeneEditorViewModel(string geneId)
        {
            GeneEditorViewModel geneEditorViewModel = geneEditorService.GetGeneEditorViewModel(geneId);
            return Json(geneEditorViewModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> DeleteGene(string geneId)
        {
            await geneEditorService.DeleteGene(geneId);

            return JsonSuccess(geneId);
        }
    }
}

Source/AutoGene/Presentation/Host/Views/Ecommerce/Index.cshtml
@{
    ViewBag.Title = "SynTau - Home";
    Layout = "~/Views/Shared/_LayoutEcommerce.cshtml";
}

<div class="row justify-content-center">
    <div class="col-xl-3 mb-3 mr-3">
        <!-- Card Flip -->
        <div class="card-flip">
            <div class="flip">
                <div class="front">
                    <!-- front content -->
                    <div class="card text-center p-3 shadow-lg border-0">
                        <img class="card-img-top img-fluid mx-auto" src="~/Content/images/genes_logo.svg" alt="Genes" style="width: 125px;">
                        <div class="card-body">
                            <p class="card-title text-card-title">Genes</p>
                            <p class="card-subtitle text-card-subtitle">Order Now<i class="fas fa-angle-right"></i></p>
                            <a href="#" class="stretched-link"></a>
                        </div>
                    </div>
                </div>
                <div class="back">
                    <!-- back content -->
                    <div class="card p-3 shadow-lg border-0">
                        <div class="card-header bg-transparent">Genes</div>
                        <div class="card-body">
                            <form method="POST" action="@Url.Action("Index", "GeneOrder")">
                                <div class="form-group">
                                    <label for="genesProjectName" class="text-uppercase text-muted">Project Name</label>
                                    <input type="text" class="form-control" id="genesProjectName" name="genesProjectName" aria-describedby="genesProjectNameHelp" placeholder="My Genes project">
                                    <small id="genesProjectNameHelp" class="form-text text-muted">Optional</small>
                                </div>
                                <button type="submit" class="btn btn-primary">Start New Project</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 mb-3 mr-3">
        <div class="card-flip">
            <div class="flip">
                <div class="front">
                    <!-- front content -->
                    <div class="card text-center p-3 shadow-lg border-0">
                        <img class="card-img-top mx-auto" src="~/Content/images/oligo_pools_logo.svg" alt="Oligo Pools" style="width: 125px;">
                        <div class="card-body">
                            <p class="card-title text-card-title">Oligo Pools</p>
                            <p class="card-subtitle text-card-subtitle">Order Now<i class="fas fa-angle-right"></i></p>
                            <a href="#" class="stretched-link"></a>
                        </div>
                    </div>
                </div>
                <div class="back">
                    <!-- back content -->
                    <div class="card p-3 shadow-lg border-0">
                        <div class="card-header bg-transparent">Oligo Pools</div>
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <label for="oligoPoolsProjectNameInput" class="text-uppercase text-muted">Project Name</label>
                                    <input type="text" class="form-control" id="oligoPoolsProjectNameInput" aria-describedby="oligoPoolsProjectNameHelp" placeholder="My Oligo Pools project">
                                    <small id="oligoPoolsProjectNameHelp" class="form-text text-muted">Optional</small>
                                </div>
                                <button type="submit" class="btn btn-primary">Start New Project</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 mb-3 mr-3">
        <div class="card-flip">
            <div class="flip">
                <div class="front">
                    <!-- front content -->
                    <div class="card text-center p-3 shadow-lg border-0">
                        <img class="card-img-top mx-auto" src="~/Content/images/libraries_logo.svg" alt="Libraries" style="width: 125px;">
                        <div class="card-body">
                            <p class="card-title text-card-title">Variant Libraries</p>
                            <p class="card-subtitle text-card-subtitle">Order Now<i class="fas fa-angle-right"></i></p>
                            <a href="#" class="stretched-link"></a>
                        </div>
                    </div>
                </div>
                <div class="back">
                    <!-- back content -->
                    <div class="card p-3 shadow-lg border-0">
                        <div class="card-header bg-transparent">Variant Libraries</div>
                        <div class="card-body">
                            <form>
                                <div class="form-group">
                                    <label for="variantLibrariesProjectNameInput" class="text-uppercase text-muted">Project Name</label>
                                    <input type="text" class="form-control" id="variantLibrariesProjectNameInput" aria-describedby="variantLibrariesProjectNameHelp" placeholder="My Variant Libraries project">
                                    <small id="variantLibrariesProjectNameHelp" class="form-text text-muted">Optional</small>
                                </div>
                                <button type="submit" class="btn btn-primary">Start New Project</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            //$(".card").hover(
            //    function() {
            //        $(this).addClass('shadow-lg').css('cursor', 'pointer'); 
            //    }, function() {
            //        $(this).removeClass('shadow-lg');
            //    }
            //); 

            //document.querySelector(".card-flip").classList.toggle("flip");
        });
    </script>
}