Source/AutoGene/Presentation/Host/Models/Navbar.cs
namespace AutoGene.Presentation.Host.Models
{
    public class Navbar
    {
        public int Id { get; set; }
        public string nameOption { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string area { get; set; }
        public string imageClass { get; set; }
        public string activeli { get; set; }
        public bool status { get; set; }
        public int parentId { get; set; }
        public bool isParent { get; set; }
    }
}

Source/AutoGene/Presentation/Host/Controllers/GeneEditor/GeneEditorController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Business.Contracts.Services.GeneEditor;
using Business.Contracts.ViewModels.GeneEditor;
using Presentation.Common.Controllers;
using Presentation.Common.Security;

namespace AutoGene.Presentation.Host.Controllers.GeneEditor
{
    //[AuthorizeUser(UserRoles = "Guest,Admin")]
    public class GeneEditorController : BaseController
    {
        private readonly IGeneEditorService geneEditorService;

        public GeneEditorController(IGeneEditorService geneEditorService)
        {
            this.geneEditorService = geneEditorService;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            GeneEditorViewModel geneEditorViewModel = await geneEditorService.GetGeneEditorViewModel();

            return View(geneEditorViewModel);
        }

        [HttpPost]
        public async Task<JsonResult> OptimizeGene(GeneEditorViewModel geneEditorViewModel)
        {
            //            if (string.IsNullOrWhiteSpace(geneEditorViewModel.ProteinInitialSequence) &&
            //                (string.IsNullOrWhiteSpace(geneEditorViewModel.DNAInitialSequence) || geneEditorViewModel.DNAInitialSequence.Length % 3 != 0))
            //            {
            //                ModelState.AddModelError(string.Empty, "Wrong sequence");
            //                return View(geneEditorViewModel);
            //            }

            //            ModelState.Clear();
            try
            {
                geneEditorViewModel = await geneEditorService.OptimizeDNASequence(geneEditorViewModel);
                return Json(geneEditorViewModel);
            }
            catch (Exception ex)
            {
                return JsonError();
            }
        }

        [HttpPost]
        public async Task<JsonResult> UpdateGeneFragments(GeneEditorViewModel geneEditorViewModel)
        {
            await geneEditorService.UpdateGeneFragments(
                geneEditorViewModel.GeneId, geneEditorViewModel.OptimizedDNASequence, 
                geneEditorViewModel.GeneFragmentLength, geneEditorViewModel.GeneFragmentOverlappingLength, 
                geneEditorViewModel.KPlusConcentration, geneEditorViewModel.DMSO);

            return JsonSuccess(geneEditorViewModel.GeneId);
        }

        [HttpGet]
        public JsonResult GetGeneEditorViewModel(string geneId)
        {
            GeneEditorViewModel geneEditorViewModel = geneEditorService.GetGeneEditorViewModel(geneId);
            return Json(geneEditorViewModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> DeleteGene(string geneId)
        {
            await geneEditorService.DeleteGene(geneId);

            return JsonSuccess(geneId);
        }
    }
}

Source/AutoGene/Presentation/Host/Controllers/IdentityController.cs
using System;
using System.Web.Mvc;
using Infrastructure.Identity.Contracts.Services;
using Infrastructure.Identity.Contracts.ViewModels;
using Presentation.Common.Controllers;
using Presentation.Common.Models;
using Presentation.Common.Security;
using Shared.Resources;

namespace AutoGene.Presentation.Host.Controllers
{
    public class IdentityController : BaseController
    {
        private readonly IAuthenticationManager authenticationManager;
        private readonly IIdentityService identityService;
        private readonly ILocalizationManager localizationManager;

        public IdentityController(IAuthenticationManager authenticationManager, IIdentityService identityService, ILocalizationManager localizationManager)
        {
            this.authenticationManager = authenticationManager;
            this.identityService = identityService;
            this.localizationManager = localizationManager;
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel user)
        {
            AuthenticationResult result = LogIn(user.Email, user.Password, user.StayLoggedInToday);
            
            if (result.IsSuccess)
            {
                return result.MustChangePassword
                           ? RedirectToAction("ChangePassword")
                           : authenticationManager.RedirectFromLoginPage(user.Email);
            }

            return View();
        }

        [HttpGet]
        public ActionResult CreateAccount()
        {
            var createAccountViewModel = new CreateAccountViewModel();
            //SetAllCountries(createAccountViewModel);

            return View(createAccountViewModel);
        }

        [HttpPost]
        public ActionResult CreateAccount(CreateAccountViewModel createAccountViewModel)
        {
            bool isAccountCreated = false;
            try
            {
                isAccountCreated = identityService.CreateAccount(createAccountViewModel);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, localizationManager.GetLocalizedString(ex.Message));
            }

            if (isAccountCreated)
            {
                AuthenticationResult result = LogIn(createAccountViewModel.Email, createAccountViewModel.Password, false);

                if (result.IsSuccess)
                {
                    return authenticationManager.RedirectFromLoginPage(createAccountViewModel.Email);
                }
            }

            //SetAllCountries(createAccountViewModel);

            return View(createAccountViewModel);
        }
        
        public ActionResult Logout()
        {
            authenticationManager.LogOut();
            return RedirectToAction("Login");
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        private AuthenticationResult LogIn(string email, string password, bool stayLoggedInToday)
        {
            AuthenticationResult result = AuthenticationResult.Error(string.Empty);
            try
            {
                result = authenticationManager.LogIn(email, password, stayLoggedInToday);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, localizationManager.GetLocalizedString(ex.Message));
            }

            return result;
        }

//        private void SetAllCountries(CreateAccountViewModel createAccountViewModel)
//        {
//            createAccountViewModel.AllCountries =
//                EnumUtil.GetValues<CountryEnum>().Select(
//                    x => new ListItem { Text = localizationManager.GetLocalizedString(x.GetDescription()), Value = (int)x }).OrderBy(x => x.Text);
//        }
    }
}

Source/AutoGene/Presentation/Host/Controllers/ManualControl/ManualControlController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoGene.Presentation.Host.Hubs;
using Business.Contracts.Services.ManualControl;
using Business.Contracts.ViewModels.Common;
using Business.Contracts.ViewModels.ManualControl;
using Data.Contracts;
using Data.Contracts.Entities.CycleEditor;
using Data.Contracts.Entities.Identity;
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;
using Presentation.Common.Controllers;
using Presentation.Common.Security;
using Shared.DTO.Responses;
using Shared.Enum;
using Shared.Framework.Collections;
using Shared.Resources;

namespace AutoGene.Presentation.Host.Controllers.ManualControl
{
    [AuthorizeUser(UserRoles = "Guest,Admin")]
    public class ManualControlController : BaseController
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IManualControlService manualControlService;
        private readonly IHubContext signalHubContext;

        public ManualControlController(IUnitOfWork unitOfWork, IManualControlService manualControlService)
        {
            this.unitOfWork = unitOfWork;
            this.manualControlService = manualControlService;
            signalHubContext = GlobalHost.ConnectionManager.GetHubContext<SignalHub>();
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            ManualControlViewModel manualControlViewModel = await manualControlService.GetManualControlViewModel();
            return View(manualControlViewModel);
        }

        [HttpPost]
        public async Task<JsonResult> ActivateValves(IEnumerable<HardwareFunctionItemViewModel> selectedValves)
        {
            if (selectedValves != null && selectedValves.Any())
            {
                manualControlService.ActivateValves(selectedValves);

                var hardwareFunctions = (await manualControlService.GetBasicHardwareFunctions()).ToList();

                hardwareFunctions.AddRange(selectedValves);

                User currentUser = manualControlService.GetCurrentUser();

                await signalHubContext.Clients.Group(currentUser.Id).addMessage(
                    new SignalMessage
                    {
                        Message = JsonConvert.SerializeObject(hardwareFunctions),
                        SignalType = SignalType.ActivateValves
                    });

                return JsonSuccess(string.Empty);
            }

            return JsonError();
        }

        [HttpPost]
        public async Task<JsonResult> DeactivateAllValves()
        {
            await manualControlService.DeactivateAllValves();

            await ExecuteHardwareFunction(HardwareFunctionType.CloseAllValves, SignalType.DeactivateAllValves);
            
            return JsonSuccess(string.Empty);
        }

        [HttpPost]
        public async Task<JsonResult> TrayOut()
        {
            await ExecuteHardwareFunction(HardwareFunctionType.TrayOut, SignalType.TrayOut);

            return JsonSuccess(string.Empty);
        }

        [HttpPost]
        public async Task<JsonResult> TrayIn()
        {
            await ExecuteHardwareFunction(HardwareFunctionType.TrayIn, SignalType.TrayIn);

            return JsonSuccess(string.Empty);
        }

        [HttpPost]
        public async Task<JsonResult> TrayLightOn()
        {
            await ExecuteHardwareFunction(HardwareFunctionType.TrayLightOn, SignalType.TrayLightOn);

            return JsonSuccess(string.Empty);
        }

        [HttpPost]
        public async Task<JsonResult> TrayLightOff()
        {
            await ExecuteHardwareFunction(HardwareFunctionType.TrayLightOff, SignalType.TrayLightOff);

            return JsonSuccess(string.Empty);
        }
        
        [HttpPost]
        public async Task<JsonResult> SetSyringePump(ManualControlViewModel manualControlViewModel)
        {
            try
            {
                User currentUser = manualControlService.GetCurrentUser();

                HardwareFunction syringePumpHardwareFunction =
                    await unitOfWork.GetAll<HardwareFunction>()
                        .SingleAsync(x => x.FunctionType == manualControlViewModel.SelectedSyringePumpFunction);

                string apiUrl;
                if (manualControlViewModel.SelectedSyringePumpFunction == HardwareFunctionType.SyringePumpDraw)
                {
                    apiUrl = string.Format(syringePumpHardwareFunction.ApiUrl,
                        manualControlViewModel.SyringePumpStepMode ? 1 : 0, manualControlViewModel.SyringePumpFlow, manualControlViewModel.SyringePumpVolume);
                }
                else
                {
                    apiUrl = string.Format(syringePumpHardwareFunction.ApiUrl,
                        manualControlViewModel.SyringePumpStepMode ? 1 : 0, manualControlViewModel.SyringePumpFlow);
                }

                await signalHubContext.Clients.Group(currentUser.Id).addMessage(
                    new SignalMessage
                    {
                        Message = apiUrl,
                        SignalType = SignalType.SyringePump
                    });

                return JsonSuccess(string.Empty);
            }
            catch (Exception ex)
            {
                return JsonError(ex.Message);
            }
        }

        [HttpPost]
        public async Task<JsonResult> ExecGSValveFunction(ManualControlViewModel manualControlViewModel)
        {
            try
            {
                User currentUser = manualControlService.GetCurrentUser();

                await signalHubContext.Clients.Group(currentUser.Id).addMessage(
                    new SignalMessage
                    {
                        Message = manualControlViewModel.SelectedGSValveFunction,
                        SignalType = SignalType.GSValve
                    });

                return JsonSuccess(string.Empty);
            }
            catch (Exception ex)
            {
                return JsonError(ex.Message);
            }
        }

        private async Task ExecuteHardwareFunction(HardwareFunctionType hardwareFunctionType, SignalType signalType)
        {
            HardwareFunctionItemViewModel hardwareFunctionItemViewModel = await manualControlService.GetHardwareFunction(hardwareFunctionType);

            User currentUser = manualControlService.GetCurrentUser();

            await signalHubContext.Clients.Group(currentUser.Id).addMessage(
                new SignalMessage
                {
                    Message = JsonConvert.SerializeObject(hardwareFunctionItemViewModel),
                    SignalType = signalType
                });
        }
    }
}

Source/AutoGene/Presentation/Host/Controllers/NavbarController.cs
using System.Linq;
using System.Web.Mvc;
using AutoGene.Presentation.Host.Domain;
using Presentation.Common.Controllers;

namespace AutoGene.Presentation.Host.Controllers
{
    public class NavbarController : BaseController
    {
        // GET: Navbar
        public ActionResult Index()
        {
            var data = new Domain.Data();
            return PartialView("_Navbar", data.navbarItems().ToList());
        }
    }
}

Source/AutoGene/Presentation/Host/Controllers/SystemMonitorController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Business.Contracts.Services.SystemMonitor;
using Business.Contracts.ViewModels.SystemMonitor;
using Presentation.Common.Controllers;
using Presentation.Common.Security;

namespace AutoGene.Presentation.Host.Controllers
{
    [AuthorizeUser(UserRoles = "Guest,Admin")]
    public class SystemMonitorController : BaseController
    {
        private readonly ISystemMonitorService systemMonitorService;

        public SystemMonitorController(ISystemMonitorService systemMonitorService)
        {
            this.systemMonitorService = systemMonitorService;
        }

        public async Task<ActionResult> Index()
        {
            SystemMonitorViewModel systemMonitorViewModel = await systemMonitorService.GetSystemMonitorViewModel(DateTimeOffset.MinValue);

            return View(systemMonitorViewModel);
        }

        [HttpGet]
        public async Task<JsonResult> GetSystemMonitorViewModel(DateTimeOffset? lastCreatedAt)
        {
            SystemMonitorViewModel systemMonitorViewModel = await systemMonitorService.GetSystemMonitorViewModel(lastCreatedAt ?? DateTimeOffset.MinValue);

            return Json(systemMonitorViewModel, JsonRequestBehavior.AllowGet);
        }
    }
}

Source/AutoGene/Presentation/Host/Views/Shared/EcommerceSitemapJS.cshtml
<script type="text/javascript">
    (function() {
        //All urls in one place
        var actions = {};

        window.actions = actions;

        actions.common = {
                rootUrl: '@Url.Content("~")',
            },
            actions.cycleEditor = {
                synthesisCycleList: actions.common.rootUrl + "api/SynthesisCycle",
                cycleStepList: actions.common.rootUrl + "api/CycleStep",
                cycleStepFunctionList: actions.common.rootUrl + "odata/CycleStepFunction",
            }
    })();
</script>

Source/AutoGene/Presentation/Host/Views/Shared/SitemapJS.cshtml
<script type="text/javascript">
    (function() {
        //All urls in one place
        var actions = {};

        window.actions = actions;

        actions.common = {
                rootUrl: '@Url.Content("~")',
            },
            actions.systemMonitor = {
                getSystemMonitorViewModel: '@Url.Action("GetSystemMonitorViewModel", "SystemMonitor")',
            },
            actions.geneEditor = {
                geneList: actions.common.rootUrl + "odata/Gene",
                optimizeGene: '@Url.Action("OptimizeGene", "GeneEditor")',
                updateGeneFragments: '@Url.Action("UpdateGeneFragments", "GeneEditor")',
                getGeneEditorViewModel: '@Url.Action("GetGeneEditorViewModel", "GeneEditor")',
                deleteGene: '@Url.Action("DeleteGene", "GeneEditor")',
            },
            actions.cycleEditor = {
                synthesisCycleList: actions.common.rootUrl + "api/SynthesisCycle",
                cycleStepList: actions.common.rootUrl + "api/CycleStep",
                cycleStepFunctionList: actions.common.rootUrl + "odata/CycleStepFunction",
            },
            actions.manualControl = {
                activateValves: '@Url.Action("ActivateValves", "ManualControl")',
                deactivateAllValves: '@Url.Action("DeactivateAllValves", "ManualControl")',
                activatedValvesList: actions.common.rootUrl + "odata/ValveFunction",

                setSyringePump: '@Url.Action("SetSyringePump", "ManualControl")',

                trayOut: '@Url.Action("TrayOut", "ManualControl")',
                trayIn: '@Url.Action("TrayIn", "ManualControl")',
                trayLightOn: '@Url.Action("TrayLightOn", "ManualControl")',
                trayLightOff: '@Url.Action("TrayLightOff", "ManualControl")',
                execGSValveFunction: '@Url.Action("ExecGSValveFunction", "ManualControl")',
            },
            actions.systemConfiguration = {
                channelConfigurationList: actions.common.rootUrl + "api/ChannelConfiguration",
                activateChannelFunctionList: actions.common.rootUrl + "odata/ActivateChannelFunction",
            },
            actions.oligoSynthesizer = {
                synthesisActivityList: actions.common.rootUrl + "api/OligoSynthesisActivity",
                synthesisCycleList: actions.common.rootUrl + "odata/OligoSynthesisCycle",
                startSynthesis: '@Url.Action("StartSynthesis", "OligoSynthesizer")',
                stopSynthesis: '@Url.Action("StopSynthesis", "OligoSynthesizer")',
                deleteSynthesisProcess: '@Url.Action("DeleteSynthesisProcess", "OligoSynthesizer")',
            },
            actions.geneSynthesizer = {
                createGeneSynthesisProcess: '@Url.Action("CreateGeneSynthesisProcess", "GeneSynthesizer")',
                updateGeneSynthesisProcess: '@Url.Action("UpdateGeneSynthesisProcess", "GeneSynthesizer")',
                synthesisActivityList: actions.common.rootUrl + "api/GeneSynthesisActivity",
                startSynthesis: '@Url.Action("StartSynthesis", "GeneSynthesizer")',
                stopSynthesis: '@Url.Action("StopSynthesis", "GeneSynthesizer")',
                deleteSynthesisProcess: '@Url.Action("DeleteSynthesisProcess", "GeneSynthesizer")',
            };
    })();
</script>

Source/AutoGene/Presentation/Host/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- DataTables CSS -->
    <link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <!-- DataTables Responsive CSS -->
    <link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/bower_components/morrisjs/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />

    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/bower_components/jquery/dist/jquery.min.js")"></script>

    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/bower_components/metisMenu/dist/metisMenu.min.js")"></script>

    <link href="@Url.Content("~/Content/kendo/2019.R2/kendo.common-material.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2019.R2/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2019.R2/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2019.R2/kendo.material.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2019.R2/kendo.dataviz.material.min.css")" rel="stylesheet" type="text/css" />
    @*<script src="@Url.Content("~/Scripts/kendo/2019.R2/jquery.min.js")"></script>*@
    <script src="@Url.Content("~/Scripts/kendo/2019.R2/jszip.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2019.R2/kendo.all.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2019.R2/kendo.aspnetmvc.min.js")"></script>

    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>

    <script src="@Url.Content("~/Scripts/jquery.signalR-2.2.1.min.js")"></script>
    <script src="@Url.Content("~/signalr/hubs")"></script>

    <script src="@Url.Content("~/Scripts/highcharts/5.0.7/highstock.src.js")"></script>
    <script src="@Url.Content("~/Scripts/highcharts/5.0.7/exporting.js")"></script>
    <script src="@Url.Content("~/Scripts/highcharts/5.0.7/offline-exporting.js")"></script>

    @Scripts.Render("~/bundles/common")
    @Scripts.Render("~/bundles/validator")
    @Scripts.Render("~/bundles/viewmodels")

    @Html.Partial("SitemapJS")

</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        @Html.Action("Index", "Navbar")

        <div id="page-wrapper">
            @RenderBody()          
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
         
    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/raphael/raphael-min.js")"></script>
 
    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")"></script>

    <!-- Custom Theme JavaScript -->
    <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

Source/AutoGene/Presentation/Host/Views/Shared/_LayoutBlog.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/blog.css")" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item active" href="#">About us</a>
            @*<a class="blog-nav-item" href="#">New features</a>
                <a class="blog-nav-item" href="#">Press</a>
                <a class="blog-nav-item" href="#">New hires</a>
                <a class="blog-nav-item" href="#">About</a>*@
        </nav>
    </div>
</div>

<div class="container">

    <div class="blog-header">
        <h1 class="blog-title">Auto Gene</h1>
        <p class="lead blog-description">Cheap automatic system for artificial gene synthesis scalable to microfluidic chip.</p>
    </div>

    <div class="row">

        @RenderBody()

        @*<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="sidebar-module sidebar-module-inset">
                <h4>About</h4>
                <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            </div>
            <div class="sidebar-module">
                <h4>Archives</h4>
                <ol class="list-unstyled">
                    <li><a href="#">January 2014</a></li>
                    <li><a href="#">December 2013</a></li>
                    <li><a href="#">November 2013</a></li>
                    <li><a href="#">October 2013</a></li>
                    <li><a href="#">September 2013</a></li>
                    <li><a href="#">August 2013</a></li>
                    <li><a href="#">July 2013</a></li>
                    <li><a href="#">June 2013</a></li>
                    <li><a href="#">May 2013</a></li>
                    <li><a href="#">April 2013</a></li>
                    <li><a href="#">March 2013</a></li>
                    <li><a href="#">February 2013</a></li>
                </ol>
            </div>
            <div class="sidebar-module">
                <h4>Elsewhere</h4>
                <ol class="list-unstyled">
                    <li><a href="#">GitHub</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                </ol>
            </div>
        </div>*@<!-- /.blog-sidebar -->

    </div><!-- /.row -->

</div><!-- /.container -->

<div class="blog-footer">
    @*<p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@@mdo</a>.</p>*@
    <p>
        <a href="#">Back to top</a>
    </p>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
</body>
</html>